apiVersion: v1
kind: LimitRange
metadata:
  name: low-resource-range
spec:
  limits:
  - default:
    cpu: 1
    memory: 500Mi
  defaultRequest:
    cpu: 0.5
    memory: 100Mi
  type: Container



---

apiVersion: batch/v1
kind: Job
metadata:
  name: sleepy
  spec:
    template:
      spec:
        containers:
        - name: resting
          image: busybox
          command: ["/bin/sleep"]
          args: ["3"]
        restartPolicy: Never